### PR TITLE
Add basic PR checks

### PR DESCRIPTION
**Pull request by smithclay**
## What is the current behavior?
* Tests/linting runs locally

## What is the new behavior?

* Tests/linting runs via GitHub action for all PRs into `main`

---

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests(`make test`) for the changes have been added (for bug fixes / features) and pass
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Lint (`make lint`) has passed locally and any fixes were made for failures

## Pull request type

Ops

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): CI

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by smithclay** [comment]
Looks like the lint failure is legitimate and there are imports for a previous repo name: 
image

**Comment by njvrzm** [comment]
Gosh, I thought for sure I'd fixed all that, sorry! Taking a look.

**Comment by smithclay** [comment]
@njvrzm now passing, thank you!

**Review by njvrzm — APPROVED** [review]
🎉 Thank you!

**Pull request merged**
